import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TemporalProvider from '@/components/custom/TemporalProvider'
import 'temporal-polyfill/global'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
console.log(Temporal.Now.zonedDateTimeISO().toString())

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <TemporalProvider>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </TemporalProvider>
  )
}
